# ----
# Site

title: ZEI API
description: Zero ecoimpact API documentation.
url: https://zero-ecoimpact.org
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "/API/"
    values:
      layout: default

types:
  - get

