# ----
# Site

title: ZEI API
description: Zei API documentation.
url: https://zei-world.com
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  plugins:
    title: Plugins
    position: 2
  api:
    title: APIs
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get

